//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 06:22:02 AM MSK 
//


package com.example.routes.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Name" use="required" type="{main.webapp.xml}string" /&gt;
 *       &lt;attribute name="Method" use="required" type="{main.webapp.xml}HttpMethodType" /&gt;
 *       &lt;attribute name="Href" use="required" type="{main.webapp.xml}string" /&gt;
 *       &lt;attribute name="ParamKind" type="{main.webapp.xml}string" /&gt;
 *       &lt;attribute name="ResultKind" type="{main.webapp.xml}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionType")
public class ActionType {

    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Method", required = true)
    protected HttpMethodType method;
    @XmlAttribute(name = "Href", required = true)
    protected String href;
    @XmlAttribute(name = "ParamKind")
    protected String paramKind;
    @XmlAttribute(name = "ResultKind")
    protected String resultKind;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link HttpMethodType }
     *     
     */
    public HttpMethodType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpMethodType }
     *     
     */
    public void setMethod(HttpMethodType value) {
        this.method = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the paramKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamKind() {
        return paramKind;
    }

    /**
     * Sets the value of the paramKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamKind(String value) {
        this.paramKind = value;
    }

    /**
     * Gets the value of the resultKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultKind() {
        return resultKind;
    }

    /**
     * Sets the value of the resultKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultKind(String value) {
        this.resultKind = value;
    }

}
