//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 06:22:02 AM MSK 
//


package com.example.routes.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkRelationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LinkRelationType"&gt;
 *   &lt;restriction base="{main.webapp.xml}string"&gt;
 *     &lt;enumeration value="Up"/&gt;
 *     &lt;enumeration value="Down"/&gt;
 *     &lt;enumeration value="Forward"/&gt;
 *     &lt;enumeration value="Backward"/&gt;
 *     &lt;enumeration value="Related"/&gt;
 *     &lt;enumeration value="Alternate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LinkRelationType")
@XmlEnum
public enum LinkRelationType {

    @XmlEnumValue("Up")
    UP("Up"),
    @XmlEnumValue("Down")
    DOWN("Down"),
    @XmlEnumValue("Forward")
    FORWARD("Forward"),
    @XmlEnumValue("Backward")
    BACKWARD("Backward"),
    @XmlEnumValue("Related")
    RELATED("Related"),
    @XmlEnumValue("Alternate")
    ALTERNATE("Alternate");
    private final String value;

    LinkRelationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LinkRelationType fromValue(String v) {
        for (LinkRelationType c: LinkRelationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
