
package xml.webapp.main;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-39ff641f3d81d8e0b9487ae8c49ac2a5bf055bc1
 * 2021-01-12T07:23:03.273+03:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
public final class LocationsEndpointPortType_LocationsEndpointPort_Client {

    private static final QName SERVICE_NAME = new QName("main.webapp.xml", "LocationsEndpointService");

    private LocationsEndpointPortType_LocationsEndpointPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LocationsEndpointService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LocationsEndpointService ss = new LocationsEndpointService(wsdlURL, SERVICE_NAME);
        LocationsEndpointPortType port = ss.getLocationsEndpointPort();

        {
        System.out.println("Invoking deleteLocation...");
        xml.webapp.main.ByIdSpecType _deleteLocation_locationDeleteByIdSpec = new xml.webapp.main.ByIdSpecType();
        port.deleteLocation(_deleteLocation_locationDeleteByIdSpec);


        }
        {
        System.out.println("Invoking getLocations...");
        xml.webapp.main.QuerySpecType _getLocations_locationsQuerySpec = new xml.webapp.main.QuerySpecType();
        xml.webapp.main.LocationsQueryResultType _getLocations__return = port.getLocations(_getLocations_locationsQuerySpec);
        System.out.println("getLocations.result=" + _getLocations__return);


        }
        {
        System.out.println("Invoking updateLocation...");
        xml.webapp.main.LocationUpdateSpecType _updateLocation_locationUpdateSpec = new xml.webapp.main.LocationUpdateSpecType();
        port.updateLocation(_updateLocation_locationUpdateSpec);


        }
        {
        System.out.println("Invoking addLocation...");
        xml.webapp.main.LocationCreationSpecType _addLocation_locationCreationSpec = new xml.webapp.main.LocationCreationSpecType();
        xml.webapp.main.LocationType _addLocation__return = port.addLocation(_addLocation_locationCreationSpec);
        System.out.println("addLocation.result=" + _addLocation__return);


        }
        {
        System.out.println("Invoking getLocationById...");
        xml.webapp.main.ByIdSpecType _getLocationById_locationQueryByIdSpec = new xml.webapp.main.ByIdSpecType();
        xml.webapp.main.LocationType _getLocationById__return = port.getLocationById(_getLocationById_locationQueryByIdSpec);
        System.out.println("getLocationById.result=" + _getLocationById__return);


        }

        System.exit(0);
    }

}
