package xml.webapp.main;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-39ff641f3d81d8e0b9487ae8c49ac2a5bf055bc1
 * 2021-01-12T07:22:59.431+03:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "main.webapp.xml", name = "RoutesEndpointPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RoutesEndpointPortType {

    @WebMethod
    @Oneway
    public void updateRoute(

        @WebParam(partName = "RouteUpdateSpec", name = "RouteUpdateSpec", targetNamespace = "main.webapp.xml")
        RouteUpdateSpecType routeUpdateSpec
    );

    @WebMethod
    @WebResult(name = "RoutesQueryResult", targetNamespace = "main.webapp.xml", partName = "RoutesQueryResult")
    public RoutesQueryResultType getRoutesByName(

        @WebParam(partName = "RoutesQueryByNameSpec", name = "RoutesQueryByNameSpec", targetNamespace = "main.webapp.xml")
        RoutesQueryByNameSpecType routesQueryByNameSpec
    );

    @WebMethod
    @WebResult(name = "RoutesQueryResult", targetNamespace = "main.webapp.xml", partName = "RoutesQueryResult")
    public RoutesQueryResultType getRoutes(

        @WebParam(partName = "RoutesQuerySpec", name = "RoutesQuerySpec", targetNamespace = "main.webapp.xml")
        QuerySpecType routesQuerySpec
    );

    @WebMethod
    @WebResult(name = "OperationStatusInfo", targetNamespace = "main.webapp.xml", partName = "OperationStatusInfo")
    public OperationStatusInfoType deleteRouteByDistance(

        @WebParam(partName = "DeleteRouteByDistanceSpec", name = "DeleteRouteByDistanceSpec", targetNamespace = "main.webapp.xml")
        DeleteRouteByDistanceSpecType deleteRouteByDistanceSpec
    );

    @WebMethod
    @WebResult(name = "DistanceSumQueryResult", targetNamespace = "main.webapp.xml", partName = "DistanceSumQueryResult")
    public DistanceQueryResultType getDistanceSum(

        @WebParam(partName = "DistanceSumQuerySpec", name = "DistanceSumQuerySpec", targetNamespace = "main.webapp.xml")
        EmptyType distanceSumQuerySpec
    );

    @WebMethod
    @WebResult(name = "Route", targetNamespace = "main.webapp.xml", partName = "Route")
    public RouteType addRoute(

        @WebParam(partName = "RouteCreationSpec", name = "RouteCreationSpec", targetNamespace = "main.webapp.xml")
        RouteCreationSpecType routeCreationSpec
    );

    @WebMethod
    @WebResult(name = "Route", targetNamespace = "main.webapp.xml", partName = "Route")
    public RouteType getRouteById(

        @WebParam(partName = "RouteQueryByIdSpec", name = "RouteQueryByIdSpec", targetNamespace = "main.webapp.xml")
        ByIdSpecType routeQueryByIdSpec
    );

    @WebMethod
    @Oneway
    public void deleteRoute(

        @WebParam(partName = "RouteDeleteByIdSpec", name = "RouteDeleteByIdSpec", targetNamespace = "main.webapp.xml")
        ByIdSpecType routeDeleteByIdSpec
    );
}
