//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.28 at 01:11:15 AM MSK 
//


package com.example.navigator.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Discoverability" type="{main.webapp.xml}DiscoverabilityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectType", propOrder = {
    "discoverability"
})
@XmlSeeAlso({
    DistanceQueryResultType.class,
    LocationServiceType.class,
    RouteServiceType.class,
    LocationsQueryResultType.class,
    RouteType.class,
    RoutesQueryResultType.class,
    LocationType.class
})
public abstract class ObjectType {

    @XmlElement(name = "Discoverability")
    protected DiscoverabilityType discoverability;

    /**
     * Gets the value of the discoverability property.
     * 
     * @return
     *     possible object is
     *     {@link DiscoverabilityType }
     *     
     */
    public DiscoverabilityType getDiscoverability() {
        return discoverability;
    }

    /**
     * Sets the value of the discoverability property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscoverabilityType }
     *     
     */
    public void setDiscoverability(DiscoverabilityType value) {
        this.discoverability = value;
    }

}
